---
# check this file with: $ yamllint .travis.yml
# travis on linux, windows, and mac
# following: https://www.scivision.dev/travis-ci-osx-python/
# https://docs.travis-ci.com/user/languages/python/
matrix:
    include:
        - os: linux
          name: "Linux/xenial - Python 3.5 (oldest supported version)"
          dist: xenial   # required for Python >= 3.7
          language: python
          sudo: required
          python:
              - 3.5
          install:
              - sudo apt-get install liblapack-dev libblas-dev gfortran
              - pip install -v .      # allantools itself, verbose output
              - pip install -r requirements.txt
          script:
              - py.test
        - os: linux
          name: "Linux/xenial - Python 3.8, (latest supported version) with coverage"
          dist: xenial   # required for Python >= 3.7
          language: python
          sudo: required
          python:
              - 3.8
          install:
              - sudo apt-get install liblapack-dev libblas-dev gfortran
              - pip install -v .      # allantools itself, verbose output
              - pip install -r requirements.txt
              - pip install coveralls
          script:
              - py.test
              - coverage run --source=allantools setup.py test
          after_success: coveralls
        - os: osx           # https://docs.travis-ci.com/user/reference/osx/
          name: "MacOS 10.14.3 - Python 3.7.2 - experimental"
          osx_image: xcode10.2  # Python 3.7.2 running on macOS 10.14.3
          language: shell       # 'language: python' is an error on Travis CI macOS
          install:
              - pip3 install -v .
              - pip3 install -r requirements.txt
          script:
              - py.test
        - os: windows
          name: "Windows - Python 3.8 - experimental"
          language: shell
          env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
          before_install:
              - choco install python --version 3.8.0
              - python --version
              - python -m ensurepip
          install:
              - python -m pip install -v .
              - python -m pip install -r requirements.txt
          script:
              - py.test
# end
